###### dein plugin settings #####

# deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'

# denite
[[plugins]]
repo = 'Shougo/denite.nvim'

# easy commentout
[[plugins]]
repo = 'tomtom/tcomment_vim'

# expantion copy and paste
[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
	nmap p <Plug>(yankround-p)
	xmap p <Plug>(yankround-p)
	nmap P <Plug>(yankround-P)
	nmap gp <Plug>(yankround-gp)
	xmap gp <Plug>(yankround-gp)
	nmap gP <Plug>(yankround-gP)
	nmap <C-p> <Plug>(yankround-prev)
	nmap <C-n> <Plug>(yankround-next)
	'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
    " #CtrlP KeyMapping
    let g:ctrlp_map = '<nop>'
    nnoremap <Space>p :CtrlP ~/<CR>
    " #CtrlP show dotfiles
    let g:ctrlp_show_hidden = 1
    " #leg g:ctrlp_dotfiles = 1
	'''

# tree file explorer
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    " # 隠しファイルを表示する
    let g:NERDTreeShowHidden = 1

	" #nnoremap <Space>N :NERDTreeToggle<CR>
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
    	'''

# cool statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
#hook_add = '''
#	let g:lightline = {
#		\ 'colorscheme': 'wombat'
#			\ }
#	" # show statusbar
#	set laststatus=2
#	" # hide --INSERT--
#	"set noshowmode
#	'''
# repo = 'baverman/vim-babymate256'
# repo = 'romainl/Apprentice'
# repo = 'mbbill/vim-seattle'
# repo = 'cocopon/iceberg.vim'


[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

# create and load vim session for tmux
# [[plugins]]
# repo = 'tpope/vim-obsession'

#[[plugins]]
#repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'tomasr/molokai'

# vim session

[[plugins]]
repo = 'xolox/vim-session'
depends = ['xolox/vim-misc']
hook_add = '''
    " # 現在のディレクトリ直下の .vimsessions/ を取得
    let s:local_session_directory = xolox#misc#path#merge(getcwd(), '.vimsessions')
    " # 存在すれば
    if isdirectory(s:local_session_directory)
      " # session保存ディレクトリをそのディレクトリの設定
      let g:session_directory = s:local_session_directory
      " # vimを辞める時に自動保存
      let g:session_autosave = 'yes'
      " # 引数なしでvimを起動した時にsession保存ディレクトリのdefault.vimを開く
      let g:session_autoload = 'yes'
      " # 1分間に1回自動保存
      let g:session_autosave_periodic = 1
    else
      " # デフォルトの保存ディレクトリを変更する(NeoVimの場合)
      let g:session_directory = '~/.config/nvim/sessions'
      let g:session_autosave = 'yes'
      let g:session_autoload = 'yes'
      let g:session_autosave_periodic = 1
    endif
    unlet s:local_session_directory
	'''
[[plugins]]
repo = 'xolox/vim-misc'

#syntax plugins
[[plugins]]
hook_add = '''
    repo = 'vim-syntastic/syntastic'
    set statusline+=%#warningmsg#
    set statusline+=%{SyntasticStatuslineFlag()}
    set statusline+=%*
    
    let g:syntastic_always_populate_loc_list = 1
    let g:syntastic_auto_loc_list = 1
    let g:syntastic_check_on_open = 1
    let g:syntastic_check_on_wq = 0
	'''
